### PR TITLE
Using deterministic collections in executor::witgen::machines

### PR DESCRIPTION
**Pull request by lvella**
Probably solves issue #199.

### CODE REVIEW

**Comment by leonardoalt** [comment]
Instead of merging `origin/main` into your feature branch, it's better if you rebase

**Comment by Schaeff** [comment]
Why not the already deterministic `BTree{Set, Map}`? Is it an optimisation?

**Comment by lvella** [comment]
> Why not the already deterministic `BTree{Set, Map}`? Is it an optimisation?

Could be, there is very little difference.

But the cost of `BTree...` is a little higher than `Hash...` (theoretically and often in practice), and since the code was already using `Hash...`, I preferred to do the least amount of change, so I just fixed the hash function.

**Comment by lvella** [comment]
> Instead of merging `origin/main` into your feature branch, it's better if you rebase which makes it easier to bring in changes in `main` and removes the merge commits in the PR.

rebased

**Comment by chriseth** [comment]
I have a bad feeling just pulling in some external dependency that is at version 0.1.0. We should rather replace the collections where it matters (and only those) by a BTreeSet / BTreeHash.

Note that speed is almost irrelevant here - this is done once during the setup phase of the witness generator.

**Pull request closed without merging**
